### ISSUE TITLE
登录的时候提示QQ版本太低。。

### ISSUE THREAD

**Issue by Aiaiioi** [duo/matrix-qq#16]
Failed to log in: 3 当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

**Comment by duo** [comment]
依赖的 MiraiGo 库进行了升级, 更新下 matrix-qq 再试试看吧

如果还不行的话, `config.yaml` 多了协议的配置
```yaml
qq:
    # QQ client protocol (1: AndroidPhone, 2: AndroidWatch, 3: MacOS, 4: QiDian, 5: IPad, 6: AndroidPad)
    protocol: 5
``` 
可以试试其它的协议
