### ISSUE TITLE
Application service has not registered this user

### ISSUE THREAD

**Issue by yamada-sexta** [duo/matrix-qq#34]
I keep getting the following error when I try to use this bot:
```
[ERROR] Failed to connect to homeserver: failed to GET /_matrix/client/versions: M_FORBIDDEN (HTTP 403): Application service has not registered this user (@qqbot:[redacted]). Retrying in 10 seconds...
```

My registration file:
```yml
id: qq
url: http://[redacted]:17777
as_token: [redacted]
hs_token: [redacted]
sender_localpart: [redacted]
rate_limited: false
namespaces:
    users:
        - regex: ^@qqbot:[redacted]$
          exclusive: true
        - regex: ^@_qq_.*:[redacted]$
          exclusive: true
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
```
There seems to be a similar issue here:
https://github.com/mautrix/whatsapp/issues/251
But I followed the steps in that issue, and it is still not working...
Does anyone else experience the same issue?
